### PR TITLE
Add credits to yusshu

### PR DESCRIPTION
**Pull request by AllanGame**
code base was created by [@yusshu](https://github.com/yusshu)

### CODE REVIEW

**Comment by iAlexT** [comment]
Nyaaa∼

**Comment by yusshu** [comment]
I'm not proud of that, but yeah

**Comment by iAlexT** [comment]
Nyaaa∼

**Comment by vCamilx** [comment]
[xd](https://github.com/Pabszito/random-sentence-bot/commit/d10f9456d439e7e0869a9ba29dd96ce112b7e232)

**Comment by AllanGame** [comment]
> [xd](https://github.com/Pabszito/random-sentence-bot/commit/d10f9456d439e7e0869a9ba29dd96ce112b7e232)

Add credits to yusshu *on README.md*

**Pull request merged**
